name: Manual Docker Build with Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Build and publish docker image'
        required: true
        default: '0.0.1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image with version and latest tags
        run: |
          docker buildx build . \
            --tag kevinonfrontend/simulator-ui:${{ inputs.tag }} \
            --tag kevinonfrontend/simulator-ui:latest \
            --load

      - name: Push Docker image tags
        run: |
          docker push kevinonfrontend/simulator-ui:${{ inputs.tag }}
          docker push kevinonfrontend/simulator-ui:latest
